name: Continuous Integration
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: Password12
  DB_HOST: localhost
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{env.DB_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASSWORD}}";' -uroot -proot
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}};' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}
      - name: Checkout Repo Code
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      # - name: Install dependencies
      #   run: go get .
      - name: Run linting
        run:  |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test
